vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       
        abonnement:
            uri_prefix: /images/abonnements
            upload_destination: '%kernel.project_dir%/public/images/abonnements'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        station:
            uri_prefix: /images/stations
            upload_destination: '%kernel.project_dir%/public/images/station'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer