vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
<<<<<<< HEAD
        blog:
            uri_prefix: /images/blog
            upload_destination: '%kernel.project_dir%/public/images/blog'
=======
        users:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
>>>>>>> c01b4c63a393e713ccc61841e7d21dc5b441e598
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
